# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRHwDAsvjX1RFlIVPt74OHGoYzMrKR5p
"""

!pip install pymupdf
!pip install pytesseract
!pip install Pillow
!pip install sentence-transformers
!pip install faiss-cpu
!pip install "pymongo[srv]"
!apt-get install poppler-utils -y

import fitz
import pytesseract
from PIL import Image
import io
import re
from pymongo import MongoClient
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss
from transformers import pipeline
import textwrap

def wrap_lines(text, width=120):
    return textwrap.fill(text, width=width)

from google.colab import drive
drive.mount('/content/drive')

!pip install pymupdf

import fitz
import pytesseract
from PIL import Image
import io

def extract_text_robust(pdf_path, ocr=True, ocr_dpi=200):
    doc = fitz.open(pdf_path)
    pages_out = []

    for pno, page in enumerate(doc, start=1):
        print(f"Processing page {pno}/{doc.page_count}...")

        try:
            txt = page.get_text("text")
        except:
            txt = ""

        if txt and len(txt.strip()) > 50:
            pages_out.append(txt.strip())
            continue

        try:
            page_dict = page.get_text("dict")
            blocks = page_dict.get("blocks", [])
        except:
            blocks = []

        blocks = sorted(blocks, key=lambda b: (b["bbox"][1], b["bbox"][0]))

        used_xrefs = set()
        page_parts = []

        for block in blocks:
            btype = block.get("type", 0)

            if btype == 0:
                t = block.get("text", "").strip()
                if t:
                    page_parts.append(t)
                    continue

            if btype == 1 and ocr:
                info = block.get("image")
                xref = info.get("xref") if isinstance(info, dict) else None

                if xref and xref not in used_xrefs:
                    used_xrefs.add(xref)
                    try:
                        pix = fitz.Pixmap(doc, xref)
                        if pix.n > 4:
                            pix = fitz.Pixmap(fitz.csRGB, pix)

                        img = Image.open(io.BytesIO(pix.tobytes("png")))
                        txt = pytesseract.image_to_string(img).strip()
                        if txt:
                            page_parts.append(txt)
                    except:
                        pass

        if not page_parts and ocr:
            try:
                pix = page.get_pixmap(dpi=ocr_dpi)
                img = Image.open(io.BytesIO(pix.tobytes("png")))
                txt = pytesseract.image_to_string(img).strip()
                if txt:
                    page_parts.append(txt)
            except:
                pass

        pages_out.append("\n".join(page_parts))

    doc.close()
    return "\n\n".join(pages_out)

PDF_PATH = "/content/drive/MyDrive/DRISHTEE_Doc.pdf"

raw_text = extract_text_robust(PDF_PATH)

print("Extracted characters:", len(raw_text))
print(raw_text[:500])

with open("/content/drive/MyDrive/extracted_text.txt", "w", encoding="utf-8") as f:
    f.write(raw_text)

print("Saved successfully!")

!pip install langchain

!pip install langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

def chunk_text(text, chunk_size=200, chunk_overlap=50):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )
    return splitter.split_text(text)

chunks = chunk_text(raw_text)

print("Total chunks:", len(chunks))

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(
    chunks,
    convert_to_numpy=True,
    show_progress_bar=True
).astype("float32")

print("Embeddings shape:", embeddings.shape)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

faiss.write_index(index, "faiss_index.bin")

print("FAISS index contains:", index.ntotal, "vectors")

from pymongo import MongoClient

MONGO_URI = "mongodb+srv://admin123:admin123@cluster0.og9wofa.mongodb.net/?retryWrites=true&w=majority"

client = MongoClient(MONGO_URI)
db = client["ragdb"]
collection = db["chunks"]

collection.delete_many({})

for i, chunk in enumerate(chunks):
    collection.insert_one({"_id": i, "text": chunk})

print("Stored", collection.count_documents({}), "chunks in MongoDB")

def clean_text(text):
    text = re.sub(r"\n+", " ", text)
    text = re.sub(r"\s{2,}", " ", text)
    return text.strip()

from transformers import pipeline

pipe = pipeline("text-generation", model="google/flan-t5-large")

def generate_answer(query):
    # Embed query
    q_embed = model.encode([query], convert_to_numpy=True).astype("float32")

    # Retrieve top-5 chunks
    D, I = index.search(q_embed, 12)

    retrieved = [clean_text(chunks[i]) for i in I[0]]
    context = "\n\n".join(retrieved).strip()

    # Prevent hallucination
    if len(context.strip()) == 0:
        return "Not available"

    prompt = f"""
    Use ONLY the context provided below to answer the question.
    If the answer is not in the context, reply exactly: Not available.
    explain in paragraphs


    Context:
    {context}

    Question: {query}

    Answer:
    """

    ans = pipe(prompt, max_new_tokens=2000)[0]["generated_text"].strip()
    return ans

QUERY = "what is 4c"

answer = generate_answer(QUERY)

print("\nFINAL ANSWER:\n")
print(wrap_lines(answer, width=120))

QUERY = "what is main goal."

answer = generate_answer(QUERY)

print("\nFINAL ANSWER:\n")
print(wrap_lines(answer, width=120))
import streamlit as st

# Page config
st.set_page_config(
    page_title="Chat with PDF",
    page_icon="📄",
    layout="wide"
)

# Custom CSS (🔥 makes it attractive)
st.markdown("""
<style>
.main {
    background-color: #0E1117;
    color: white;
}
.stTextInput>div>div>input {
    background-color: #262730;
    color: white;
}
.stFileUploader {
    background-color: #262730;
    border-radius: 10px;
    padding: 10px;
}
.big-title {
    font-size: 40px;
    font-weight: bold;
    text-align: center;
    color: #4CAF50;
}
.subtitle {
    text-align: center;
    font-size: 18px;
    color: #aaaaaa;
}
.chat-box {
    background-color: #1E1E1E;
    padding: 15px;
    border-radius: 10px;
    margin-bottom: 10px;
}
</style>
""", unsafe_allow_html=True)

# Title
st.markdown('<div class="big-title">🤖 Chat with Your PDF</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Upload a document and ask anything!</div>', unsafe_allow_html=True)

st.divider()

# Layout
col1, col2 = st.columns([1, 2])

# Sidebar / Upload section
with col1:
    st.subheader("📂 Upload Document")
    uploaded_file = st.file_uploader("Upload your PDF", type=["pdf"])

    if uploaded_file:
        st.success("✅ File uploaded successfully!")

# Chat section
with col2:
    st.subheader("💬 Ask Questions")

    query = st.text_input("Type your question here...")

    if query:
        st.markdown(f"""
        <div class="chat-box">
        <b>👤 You:</b> {query}
        </div>
        """, unsafe_allow_html=True)

        # Replace this with your actual answer function
        answer = "Processing... (connect your RAG here)"

        st.markdown(f"""
        <div class="chat-box">
        <b>🤖 AI:</b> {answer}
        </div>
        """, unsafe_allow_html=True)